#!/usr/bin/env python3
"""
Obsidian — the student side's dark look. Writes the generated part of
learn/obsidian.css.

The light stylesheets are written mostly in tokens (--paper, --ink, ...), and
obsidian.css re-points those. But a few hundred colours are written as
literals — a pale green behind a right answer, a hairline at 8% black — and a
token swap cannot reach them. This reads every student-facing stylesheet,
finds each declaration that uses a literal colour, and writes the same
declaration again for the dark look, under html[data-look="obsidian"], with
the colour translated by what it is doing:

  a surface       white and near-white become the dark surfaces, a pale tint
                  becomes the same hue as a translucent wash
  text            dark greys become light ones (and the order of emphasis is
                  kept), deep coloured text becomes the same hue, lighter
  a line          a light grey hairline becomes a white one at low alpha
  a shadow        deeper, because a shadow on a dark page has to be
  an accent       the same hue, lifted to read on a dark page

A rule that paints a dark button with white text becomes a light button with
dark text, which is what a primary button is on a dark page.

Run it again whenever a student-facing stylesheet changes:

    python3 tools/obsidian.py

Everything outside the generated block in learn/obsidian.css is written by
hand and is left exactly as it is.
"""
import colorsys
import os
import re
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "learn")
OUT = os.path.join(ROOT, "obsidian.css")
BEGIN = "/* ===== generated by tools/obsidian.py — do not edit by hand ===== */"
END = "/* ===== end of generated ===== */"
SCOPE = 'html[data-look="obsidian"]'

# Stylesheets, and the line ranges of each that only the console (admin,
# teacher) draws. Nothing is lost by including a console rule — it simply
# never matches on a student page — but leaving them out keeps the file small.
SHEETS = [
    ("app.css", [
        ("/* ==========================================================================\n   The class gradebook.",
         "/* ==========================================================================\n   What a teacher has set."),
        ("/* ============================================================ Assessment Admin", None),
    ]),
    ("oplo-chrome.css", []),
    ("exam.css", []),
    ("checks.css", []),
    ("challenge.css", []),
    ("lab/lab.css", []),
]

# Stylesheets that draw their own dark look (lab.css has one under
# html[data-look="obsidian"] already). Only the blue fills are taken from
# them, below.
FILLS_ONLY = {"lab/lab.css"}

# A blue fill with white text on it. On the dark page --blue is lifted so
# that blue text reads (#409cff), which is too light to carry white text; a
# fill takes the deeper blue instead, so the label on it keeps 4.5:1.
FILL = {"var(--blue)": "var(--fill)", "var(--blue-d)": "var(--fill-d)"}

# Dark surfaces, lightest last.
BG = (21, 22, 24)        # #151618 Obsidian — the page
S1 = (28, 29, 33)        # a card
S2 = (34, 35, 40)        # a raised fill inside a card
S3 = (42, 43, 49)        # a pressed or hovered fill
S4 = (54, 55, 62)        # a control's track
ELEV = (44, 45, 51)      # a panel that was ink-dark in the light look
INK = (245, 245, 247)

# Panels that are dark in the light look (background: var(--ink), white
# text). Here they stay dark — a step above the page — rather than turning
# into slabs of white. Their insides were designed for a dark panel already,
# so nothing below them is generated; obsidian.css handles them by hand.
BANNERS = [".lx-resume", ".lx-next", ".lx-today-strip", ".xc-screen", ".lx-toast",
           ".km-flag", ".gr-tip", ".lx-user .av", ".lx-acct-head .av"]
# Things that are dark in the light look on purpose — the selection
# toolbar, the picture viewer, a video, a title card — are already right on a
# dark page. Nothing in or under them is generated.
KEEP_DARK = [".rd-fig-hint", ".rd-zoom", ".rd-tools", ".rd-video", ".rd-vph", ".tt-open", ".lx-xp", ".ch-tc"]
# Controls that are dark in the light look become light ones, with dark text.
CONTROL = re.compile(r"btn|button|\bgo\b|-go\b|pill|chip|opt|-seg|-sc\b|tool|mapbtn|onion|kinds|send|"
                     r"pd-next|rt-next|copy|pick|tile|-rn\b|cell|\.n\b|primary|submit|filter|strong")


# ---------------------------------------------------------------- colours
NAMED = {"white": (255, 255, 255, 1.0), "black": (0, 0, 0, 1.0)}
COLOR_RE = re.compile(
    r"#[0-9a-fA-F]{8}\b|#[0-9a-fA-F]{6}\b|#[0-9a-fA-F]{4}\b|#[0-9a-fA-F]{3}\b"
    r"|rgba?\(\s*[\d.]+%?\s*,?\s*[\d.]+%?\s*,?\s*[\d.]+%?\s*(?:[,/]\s*[\d.]+%?\s*)?\)"
    r"|\bwhite\b|\bblack\b")


def parse_color(tok):
    t = tok.strip().lower()
    if t in NAMED:
        return NAMED[t]
    if t.startswith("#"):
        h = t[1:]
        if len(h) in (3, 4):
            h = "".join(c * 2 for c in h)
        r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
        a = int(h[6:8], 16) / 255 if len(h) == 8 else 1.0
        return (r, g, b, a)
    nums = re.findall(r"[\d.]+%?", t)
    def ch(x):
        return float(x[:-1]) * 2.55 if x.endswith("%") else float(x)
    r, g, b = ch(nums[0]), ch(nums[1]), ch(nums[2])
    a = 1.0
    if len(nums) > 3:
        a = float(nums[3][:-1]) / 100 if nums[3].endswith("%") else float(nums[3])
    return (r, g, b, a)


def fmt(r, g, b, a=1.0):
    r, g, b = (int(round(max(0, min(255, v)))) for v in (r, g, b))
    if a >= 0.999:
        return "#%02x%02x%02x" % (r, g, b)
    return "rgba(%d,%d,%d,%s)" % (r, g, b, ("%.3f" % a).rstrip("0").rstrip("."))


def hls(c):
    return colorsys.rgb_to_hls(c[0] / 255, c[1] / 255, c[2] / 255)


def from_hls(h, l, s):
    r, g, b = colorsys.hls_to_rgb(h, max(0, min(1, l)), max(0, min(1, s)))
    return (r * 255, g * 255, b * 255)


def neutral(c):
    """Grey, near enough: Apple's greys lean a hair blue, a pale tint does not."""
    h, l, s = hls(c)
    chroma = max(c[:3]) - min(c[:3])
    return chroma <= 7 or s < 0.1


def lum(c):
    return hls(c)[1]


def mix(a, b, t):
    return tuple(a[i] + (b[i] - a[i]) * t for i in range(3))


def vivid(c, l=0.62, smin=0.72):
    """The same hue, at a lightness that reads on a dark page."""
    h, _, s = hls(c)
    return from_hls(h, l, max(s, smin))


# --------------------------------------------------------------- roles
def as_surface(c):
    r, g, b, a = c
    L = lum(c)
    if neutral(c):
        if a < 0.999:
            if L > 0.9:
                # Mostly-opaque white is glass; faint white was already a
                # light laid over something dark, and stays one.
                return fmt(*S1, a=min(1, a * 0.95 + 0.02)) if a >= 0.5 else fmt(r, g, b, a)
            if L < 0.2:        # black: a scrim stays a scrim, a faint shade becomes a faint light
                return fmt(0, 0, 0, a=min(0.85, a * 1.3)) if a >= 0.3 else fmt(255, 255, 255, a=min(0.14, a * 0.9 + 0.012))
            return fmt(255, 255, 255, a=min(0.2, a * 0.5))
        if L >= 0.995: return fmt(*S1)
        if L >= 0.955: return fmt(*S2)
        if L >= 0.915: return fmt(*S3)
        if L >= 0.86:  return fmt(*mix(S3, S4, 0.5))
        if L >= 0.74:  return fmt(*S4)
        if L >= 0.45:  return fmt(*from_hls(hls(c)[0], 0.30 + (L - 0.45) * 0.35, hls(c)[2]))
        if L >= 0.22:  return fmt(*from_hls(hls(c)[0], L + 0.05, hls(c)[2]))
        return None        # a dark surface: handled with its text by flip()
    h, _, s = hls(c)
    if L >= 0.84:          # a pale tint: the hue as a wash
        alpha = max(0.08, min(0.3, (1 - L) * 1.5 + 0.05)) * (a if a < 1 else 1)
        return fmt(*vivid(c, 0.56), a=alpha)
    if a < 0.999:          # a translucent accent keeps its alpha, brighter
        return fmt(*vivid(c, max(L, 0.55)), a=min(0.9, a * 1.25))
    if L < 0.5:            # a deep accent fill: lifted
        return fmt(*from_hls(h, min(0.62, L + 0.14), max(s, 0.6)))
    return fmt(*from_hls(h, min(L, 0.7), s))


def as_text(c):
    r, g, b, a = c
    L = lum(c)
    if neutral(c):
        if L >= 0.97:
            return None        # white text: already on something dark or coloured
        if L < 0.3:
            v = 0.96 - L * 0.4
        elif L <= 0.78:
            v = max(0.4, min(0.84, 1.08 - L))
        else:
            v = 0.4
        return fmt(*from_hls(0.66, v, 0.03), a=a)
    if L >= 0.85:
        return None            # light coloured text is already on something dark
    h, _, s = hls(c)
    return fmt(*from_hls(h, max(0.68, min(0.8, 1.2 - L)), max(s, 0.7)), a=a)


def as_line(c):
    r, g, b, a = c
    L = lum(c)
    if neutral(c):
        if L > 0.6:
            if a < 0.999:
                return fmt(255, 255, 255, a=min(0.22, (1 - L) * a + 0.04)) if L < 0.97 else fmt(255, 255, 255, a=min(0.18, a * 0.25))
            return fmt(255, 255, 255, a=max(0.07, min(0.24, (1 - L) * 0.95 + 0.035)))
        if L < 0.2:
            if a < 0.999:
                return fmt(255, 255, 255, a=min(0.3, a * 1.25 + 0.02))
            return fmt(*INK, a=0.9)
        return fmt(255, 255, 255, a=0.24)
    if lum(c) > 0.8:           # a pale tinted line: the hue, faint
        return fmt(*vivid(c, 0.6), a=0.34 * (a if a < 1 else 1))
    return fmt(*vivid(c, 0.62), a=min(1, a * (1.2 if a < 1 else 1)))


def as_shadow_color(c):
    r, g, b, a = c
    if neutral(c) and lum(c) < 0.25:
        return fmt(0, 0, 0, a=min(0.6, a * 2.3 + 0.04))
    if neutral(c) and lum(c) > 0.9:
        return fmt(255, 255, 255, a=min(0.06, a * 0.12))
    return fmt(*vivid(c, 0.58), a=min(0.6, a * 1.3))


def as_accent(c):
    if neutral(c):
        return as_surface(c)
    L = lum(c)
    h, _, s = hls(c)
    r, g, b, a = c
    if L < 0.5:
        return fmt(*from_hls(h, min(0.64, L + 0.14), max(s, 0.6)), a=a)
    return fmt(*c[:3], a=a)


# -------------------------------------------------------- declarations
SURFACE = {"background", "background-color", "background-image", "fill"}
TEXT = {"color", "-webkit-text-fill-color", "caret-color"}
LINE = {"border", "border-color", "border-top", "border-bottom", "border-left", "border-right",
        "border-top-color", "border-bottom-color", "border-left-color", "border-right-color",
        "border-block", "border-inline", "border-block-end", "border-block-start", "border-inline-start",
        "border-inline-end", "outline", "outline-color", "text-decoration", "text-decoration-color",
        "column-rule", "stroke", "border-image"}
SHADOW = {"box-shadow", "text-shadow", "filter", "-webkit-box-shadow"}


def split_top(v, sep=","):
    out, depth, cur = [], 0, ""
    for ch in v:
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        if ch == sep and depth == 0:
            out.append(cur)
            cur = ""
        else:
            cur += ch
    out.append(cur)
    return out


def map_value(prop, value, rule_ctx):
    if "url(" in value or "var(" in value and not COLOR_RE.search(value):
        return None
    p = prop.lower()
    if p.startswith("--"):
        role = custom_role(p)
    elif p in SURFACE or p == "background-image":
        role = "surface"
    elif p in TEXT:
        role = "text"
    elif p in LINE:
        role = "line"
    elif p in SHADOW:
        role = "shadow"
    elif p in ("accent-color",):
        role = "accent"
    else:
        return None

    if role == "shadow":
        parts = []
        for sh in split_top(value):
            toks = sh.strip()
            m = COLOR_RE.search(toks)
            if not m:
                parts.append(toks)
                continue
            c = parse_color(m.group(0))
            nums = re.findall(r"-?[\d.]+px|\b0\b", toks.replace(m.group(0), ""))
            ring = "inset" in toks and len(nums) >= 3 and all(re.match(r"^0(px)?$", n) for n in nums[:3]) \
                or (len(nums) == 4 and all(re.match(r"^0(px)?$", n) for n in nums[:3]))
            new = as_line(c) if ring else as_shadow_color(c)
            parts.append(toks.replace(m.group(0), new))
        out = ", ".join(parts)
        return out if out != value.strip() else None

    def repl(m):
        c = parse_color(m.group(0))
        if role == "surface":
            n = as_surface(c)
            if n is None:
                # A dark surface. On hover it was a light button going darker,
                # so here it goes lighter; with light text on it, it is meant
                # to be dark (a video, a title card) and stays; alone, it is
                # ink (a dot, a bar) and turns light.
                if rule_ctx.get("hover"):
                    n = "#ffffff"
                elif rule_ctx.get("video") or rule_ctx.get("light_text"):
                    n = m.group(0)
                else:
                    n = fmt(*INK)
        elif role == "text":
            n = as_text(c)
            if n is None:
                n = fmt(*BG) if rule_ctx.get("control_ink") else m.group(0)
        elif role == "line":
            n = as_line(c)
        elif role == "accent":
            n = as_accent(c)
        elif role == "custom-line":
            n = as_line(c)
        elif role == "custom-text":
            n = as_text(c) or m.group(0)
        else:
            n = as_surface(c) or fmt(*S4)
        return n
    out = COLOR_RE.sub(repl, value)
    return out if out.strip() != value.strip() else None


def custom_role(name):
    if re.search(r"grid|axis|track|rule|hair|line|border", name):
        return "custom-line"
    if re.search(r"ink|text|fg", name):
        return "custom-text"
    if re.search(r"hue|accent|blue|green|orange|red|amber|good|bad|mc$|-c$", name):
        return "accent"
    return "surface"


# ----------------------------------------------------------------- CSS
def strip_comments(s):
    return re.sub(r"/\*.*?\*/", "", s, flags=re.S)


def parse_blocks(s):
    """[(prelude, body)] at one level; body is a string."""
    out, i, n = [], 0, len(s)
    while i < n:
        j = s.find("{", i)
        if j < 0:
            break
        prelude = s[i:j].strip()
        depth, k = 1, j + 1
        while k < n and depth:
            if s[k] == "{":
                depth += 1
            elif s[k] == "}":
                depth -= 1
            k += 1
        out.append((prelude, s[j + 1:k - 1]))
        i = k
    return out


def decls(body):
    out = []
    for d in split_top(body, ";"):
        if ":" not in d:
            continue
        p, v = d.split(":", 1)
        out.append((p.strip(), v.strip()))
    return out


def scope_selector(sel):
    parts = []
    for s in split_top(sel):
        s = s.strip()
        if not s:
            continue
        if s.startswith(":root"):
            parts.append(SCOPE + s[5:])
        elif re.match(r"^html\b", s):
            parts.append(SCOPE + s[4:])
        else:
            parts.append(SCOPE + " " + s)
    return ",\n".join(parts)


def rule_context(prelude, ds):
    ctx = {}
    bgs = [v for p, v in ds if p.lower() in ("background", "background-color")]
    cols = [v for p, v in ds if p.lower() == "color"]
    for c in cols:
        m = COLOR_RE.search(c)
        if m and lum(parse_color(m.group(0))) > 0.8:
            ctx["light_text"] = True
    sels = [x.strip() for x in split_top(prelude)]
    ctx["hover"] = bool(re.search(r":hover|:active", prelude))
    ctx["video"] = "video" in prelude
    if any("var(--ink)" in b for b in bgs):
        if any(x in BANNERS for x in sels):
            ctx["banner"] = True
        elif CONTROL.search(prelude):
            ctx["control_ink"] = True
    return ctx


def kept_dark(prelude):
    for x in split_top(prelude):
        x = x.strip()
        for k in KEEP_DARK:
            if x == k or re.match(re.escape(k) + r"(?![\w-])", x):
                return True
    return False


def under_banner(prelude):
    for x in split_top(prelude):
        x = x.strip()
        for b in BANNERS:
            if x.startswith(b + " ") or x.startswith(b + ">") or x.startswith(b + ":") or x.startswith(b + "::"):
                return True
    return False


def generate(sheet, css, skip_ranges):
    # Drop console-only stretches.
    for start, end in skip_ranges:
        a = css.find(start)
        if a < 0:
            sys.exit("obsidian.py: marker not found in %s: %r" % (sheet, start[:60]))
        b = css.find(end, a + 1) if end else len(css)
        if b < 0:
            sys.exit("obsidian.py: end marker not found in %s: %r" % (sheet, end[:60]))
        css = css[:a] + css[b:]
    css = strip_comments(css)
    lines = []

    def walk(blocks, indent=""):
        for prelude, body in blocks:
            if prelude.startswith("@keyframes") or prelude.startswith("@font-face") or prelude.startswith("@-webkit-keyframes"):
                continue
            if prelude.startswith("@media") or prelude.startswith("@supports") or prelude.startswith("@container"):
                inner = []
                saved = len(lines)
                walk(parse_blocks(body), indent + "  ")
                if len(lines) > saved:
                    block = lines[saved:]
                    del lines[saved:]
                    lines.append(indent + prelude + " {")
                    lines.extend(block)
                    lines.append(indent + "}")
                continue
            if prelude.startswith("@"):
                continue
            if ".ld" in prelude or under_banner(prelude) or kept_dark(prelude):
                continue
            ds = decls(body)
            if sheet in FILLS_ONLY:
                out = ["%s  %s: %s;" % (indent, p, FILL[v.strip()]) for p, v in ds
                       if p.lower() in ("background", "background-color") and v.strip() in FILL]
                if out:
                    lines.append(indent + scope_selector(prelude).replace("\n", "\n" + indent) + " {")
                    lines.extend(out)
                    lines.append(indent + "}")
                continue
            ctx = rule_context(prelude, ds)
            out = []
            if ctx.get("banner"):
                out.append("%s  background: %s;" % (indent, fmt(*ELEV)))
            for p, v in ds:
                if p.lower() in ("--paper", "--canvas", "--sunk", "--ink", "--ink-2", "--ink-3", "--rule",
                                 "--hair", "--blue", "--blue-d", "--green", "--amber", "--red") and ":root" in prelude:
                    continue    # the tokens themselves are set by hand
                imp = ""
                vv = v
                if vv.lower().endswith("!important"):
                    imp = " !important"
                    vv = vv[: -len("!important")].strip()
                if p.lower() in ("background", "background-color") and vv in FILL:
                    out.append("%s  %s: %s%s;" % (indent, p, FILL[vv], imp))
                    continue
                if not COLOR_RE.search(vv):
                    # A dark-surface rule's white text is flipped even when the
                    # surface is a token (var(--ink) on a primary button).
                    continue
                n = map_value(p, vv, ctx)
                if n is not None:
                    out.append("%s  %s: %s%s;" % (indent, p, n, imp))
            # A control that is ink-dark in the light look is light here, so
            # its text goes dark — even when the rule leaves the colour to
            # another rule (.ex-btn.submit takes its white from .primary).
            if ctx.get("control_ink") and not any(o.strip().startswith("color:") for o in out):
                if not any(p.lower() == "color" and "var(--paper)" in v for p, v in ds):
                    out.append("%s  color: %s;" % (indent, fmt(*BG)))
            if out:
                lines.append(indent + scope_selector(prelude).replace("\n", "\n" + indent) + " {")
                lines.extend(out)
                lines.append(indent + "}")

    walk(parse_blocks(css))
    return "/* ---- " + sheet + " */\n" + "\n".join(lines) + "\n"


def main():
    parts = []
    for sheet, skips in SHEETS:
        css = open(os.path.join(ROOT, sheet), encoding="utf-8").read()
        parts.append(generate(sheet, css, skips))
    gen = BEGIN + "\n" + "\n".join(parts) + END
    try:
        cur = open(OUT, encoding="utf-8").read()
    except FileNotFoundError:
        sys.exit("obsidian.py: learn/obsidian.css is missing; it holds the hand-written part")
    a, b = cur.find(BEGIN), cur.find(END)
    if a < 0 or b < 0:
        sys.exit("obsidian.py: learn/obsidian.css has no generated block markers")
    new = cur[:a] + gen + cur[b + len(END):]
    if new != cur:
        open(OUT, "w", encoding="utf-8").write(new)
    print("obsidian.css: %d generated rules" % gen.count(" {\n") if False else "obsidian.css: %d lines generated" % gen.count("\n"))


if __name__ == "__main__":
    main()
